site:
  title: Router examples
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://pwright.github.io/qdr-examples/
  start_page: router-examples::index.adoc
content:
  sources:
  - url: ./
    branches: HEAD

ui:
  bundle:
    url: ./ui-preview-bundle.zip
    snapshot: true

output:
  dir: ./docs

asciidoc:
  attributes:
    plantuml-server-url: 'http://www.plantuml.com/plantuml'
    plantuml-fetch-diagram: true
    mod-loc: ROOT:partial$
